### PR TITLE
Add default implementations of IClock

### PR DESCRIPTION
**Pull request by matt-richardson**
So we don't have to copy them round everywhere

Copied from Shared as at https://github.com/OctopusDeploy/OctopusShared/blob/c0b8f82aeac54e79cbba76bec9901378491c67f8/source/Octopus.Shared/Time/FixedClock.cs.

Relies on #9 being merged first.

Reviewer note:
This library previously contained only contracts... But it seemed less than ideal to keep copying round the implementations when they're unlikely to change much. Is there a better approach here?

Once merged:
* pull this change into Server/Tentacle
* remove the implementations from Shared.
* pull this change into ReleaseBot
* consider pulling the change into Octofront (though I think there are some different things happening over there around nodatime)

### CODE REVIEW

**Review by droyad — APPROVED** [review]
While we're updating this, should we add `net5.0` as an additional target framework?

**Comment by matt-richardson** [comment]
> While we're updating this, should we add `net5.0` as an additional target framework?

Sounds a reasonable proposal. Not sure of the exact incantation though.

**Comment by droyad** [comment]
https://github.com/OctopusDeploy/CoreUtilities/pull/5/files#diff-5ab8454ee335282efe1031c1f2a0a6fd30e3a0b0289e14347d3802d6ab1557b4R3

**Review by slewis74 — APPROVED** [review]
This seems reasonable to me. SystemClock certainly makes sense here.
In other libraries we've created a separate package, something like `Octopus.Tests.Time`, for things that come out of a library that help with testing. Going to that trouble for `FixedClock` feels like it would be massive overkill.

**Pull request merged**
